---
title: "Bootstap Lasso"
author: "Ian McCarthy"
date: "2024-08-15"
output: html_document
---

Goal is to bootstrap lasso version of the model in order to determine the CI/Stability around which vars get put to 0

Installing Necessary packages
```{r}
library(bootnet)
library(qgraph)
library(tidyverse)
library(glmnet)
library(lavaan)
library(gridExtra)
library(reshape2)

# Function for getting the bootstrapped confidence intervals from the data produced by the bootstrapping function
boot_confidence_interval <- function(data){
  
  lower_bound <- quantile(data,probs=c(0.025,0.975))[[1]]
  upper_bound <- quantile(data,probs=c(0.025,0.975))[[2]]
  
  return(c(lower_bound, upper_bound))
}
```

To get full bootstrap, not just zeros:

```{r}

#######################################
# L1 Stability Bootstrapping Function #
#######################################


bootLasso <- function(designMat, # matrix of survey item labels, size k (parameters) x t (time points)
                      data,      # sample data
                      nBoots,    # number of bootstrap iterations
                      sample_model # L1-derived model fit on sample data
                      )
  {
  
  # Initialize lists in order to extract the edge weights and lambdas
  AdjMatList <- NULL 
  lambdaList <- NULL
  
  # Number of parameters
  k <- nrow(designMat) 
  
  bootList <- list()
  lassoList <- list()
  
  # Loop iterating for each new bootstrap iteration
  for (x in 1:nBoots){
    
    # Generate a vector of indices, sampling with replacement from the range of the sample size
    random_vector <- sample(1:nrow(data), 
                            size = nrow(data), 
                            replace = TRUE)
    
    # Extract the data used for this specific bootstrap iteration
    boot_sample <- data[random_vector,]
    
    # Creates a lasso model for every every pair of items across timepoints,
    # this is copied from (2) in the CLPN code
    for (t in 1:(ncol(designMat) -1)){
    
    predictors <- as.matrix(boot_sample[, designMat[, t]]) 
    
    adjMat <- matrix(0, k, k)
    colnames(adjMat) <- designMat[, (t+1)]
    rownames(adjMat) <- colnames(predictors)
    
    lambdaVec <- rep(0,k)
      
      for (i in 1:k){
      
        # Set the seed to ensure each bootstrap iteration has a new seed, but 
        # the lasso derivation within each iteration retains the same seed 
        set.seed(x) 
        
        lassoreg <- cv.glmnet(x = predictors, 
                            y = boot_sample[, designMat[i , t+1 ]], 
                            family = "gaussian", alpha = 1, standardize=TRUE) # regress each i variable in data on the predictors
      
        lambdaVec[i] <- lassoreg$lambda.min # take the smallest lambda
      
        adjMat[1:k,i] <- coef(lassoreg, s = lambdaVec[i], exact = FALSE)[2:(k+1)] # store the coefficients generated by lasso
      }
    
    AdjMatList[[t]] <- adjMat # store edge weights
    lambdaList[[t]] <- lambdaVec # store lambda
    
    
    } 
    
    # compile everything into a list for the current bootstrap iteration
    lassoList = list(Betas = melt(AdjMatList),
                     Lambdas = lambdaList)
    

    # Stores the list of edge weights, zeros, lambdas per unique bootstrap iteration
    bootList[[x]] = lassoList
   
  
  }

  
  # Create matrix of betas into one overall matrix with the items regressed, time interval, and beta value
  sample_melted <- melt(sample_model[["B"]])
  
  # Create matrix to store the distribution of each parameter
  parameter_count <- k * k * (ncol(designMat) -1 )
  grouped_betas <- matrix(nrow = parameter_count, ncol = nBoots)
  
  # Fill each row of the parameter matrix with each distribution of bootstrapped parameter estimates
  for (x in 1:parameter_count){
    for (i in 1:nBoots){
      grouped_betas[x,i] <- bootList[[i]][["Betas"]][x,3]
    }
  }
  

  # Create dataframe with the particular item, timepoint, sample estimate, bootstrapped mean, lower bound and upper bound
  boot_output <- data.frame("Item Regressed" = c(paste(bootList[[1]][["Betas"]][,2], 
                                                       bootList[[1]][["Betas"]][,1], 
                                                       sep = "~")),
                            "Time" = c(rep(1, 289), rep(2,289), rep(3,289)),
                            "Sample" = c(sample_melted[,3]),
                            "BS Mean" = c(rep(NA, 867)),
                            "LB" = c(rep(NA, 867)),
                            "UB" = c(rep(NA, 867)))
  

  # Find the mean and CI's for each and put them into the data frame
  for (x in 1:867){
    boot_output[x,4] <- mean(grouped_betas[[x]])
    boot_output[x,5] <- boot_confidence_interval(grouped_betas[x,])[[1]]
    boot_output[x,6] <- boot_confidence_interval(grouped_betas[x,])[[2]]
  }
  
  #final list of the summary df and the distributions
  all_info <- list("Summary DF" = boot_output, 
                   "Beta Distributions" = as.data.frame(grouped_betas))
  return(all_info) 
} 



# Function for generating the plots - currently fit to the sample data, not for general use
plot_CIs <- function(CIs){
  
  
  
  time1_plot <- ggplot(data = CIs[1:289,], aes(y = reorder(Item.Regressed, Sample))) + 
    geom_errorbar(aes(xmin = LB, xmax = UB),col = 'darkgrey', width = 0.2) + 
    geom_point(aes(x = Sample), color = 'red', labels = F) +
    geom_vline(aes(xintercept = 0), col = 'black') +
    labs(title = "Time 1: Lasso Beta 95% CIs", 
         x = "Bootstrapped B",
         y = "Item Regressed") + 
    theme(axis.text.y=element_blank()) 
  
  time2_plot <- ggplot(data = CIs[290:578,], aes(y = reorder(Item.Regressed, Sample))) + 
    geom_errorbar(aes(xmin = LB, xmax = UB),col = 'darkgrey', width = 0.2) + 
    geom_point(aes(x = Sample), color = 'red', labels = F) +
    geom_vline(aes(xintercept = 0), col = 'black') +
    labs(title = "Time 2: Lasso Beta 95% CIs", 
         x = "Bootstrapped B",
         y = "Item Regressed") + 
    theme(axis.text.y=element_blank()) 
  
  time3_plot <- ggplot(data = CIs[579:867,], aes(y = reorder(Item.Regressed, Sample))) + 
    geom_errorbar(aes(xmin = LB, xmax = UB),col = 'darkgrey', width = 0.2) +
    geom_point(aes(x = Sample), color = 'red', labels = F) +
    geom_vline(aes(xintercept = 0), col = 'black') +
    labs(title = "Time 3: Lasso Beta 95% CIs", 
         x = "Bootstrapped B",
         y = "Item Regressed") + 
    theme(axis.text.y=element_blank()) 
  
  all_plots <- grid.arrange(time1_plot,time2_plot,time3_plot, ncol = 3)  # 3 columns side by side
  ggsave("all_plots.png", arrangeGrob(time1_plot,time2_plot,time3_plot, ncol = 3), width = 15, height = 5)
  return(all_plots)
}

```



```{r}
# Example
bootFinal_all <- bootLasso(designMat = designMat,
          data = myfulldata, 
          nBoots = 1000,
          sample_model = glmModel)

beta_dist <- bootFinal_all[[2]]
boot_summary <- bootFinal_all[[1]]


plots_all <- plot_CIs(bootFinal_all[[1]])
```


